"""Base message classes for actor communication.

Provides the Message base class and basic message types (UserMessage, ResultMessage)
for actor-to-actor communication. Preserves v1 message structure.

Source: akgentic-framework/libs/akgentic/akgentic/core/messages/message.py
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any, Literal

from pydantic import Field, model_serializer

from akgentic.actor_address import ActorAddress
from akgentic.utils.serializer import SerializableBaseModel, serialize_base_model


def date_time_factory() -> datetime:
    """Create UTC timestamp for message creation time.

    Returns:
        Current datetime in UTC timezone.
    """
    return datetime.now(UTC)


class Message(SerializableBaseModel):
    """Base class for all actor messages.

    Preserves v1 message structure for behavioral compatibility.
    Inherits serialization/deserialization from SerializableBaseModel.

    Attributes:
        id: Unique message identifier (auto-generated UUID).
        parent_id: ID of parent message for conversation threading.
        team_id: Team identifier for multi-team routing.
        timestamp: Message creation time (auto-generated UTC).
        sender: Actor address of the message sender.
        display_type: Message display category for UI rendering.
    """

    id: uuid.UUID = Field(default_factory=uuid.uuid4)
    parent_id: uuid.UUID | None = Field(default=None)
    team_id: uuid.UUID | None = Field(default=None)
    timestamp: datetime | None = Field(default_factory=date_time_factory)
    sender: ActorAddress | None = Field(default=None)
    display_type: Literal["human", "ai", "other"] = Field(default="other")

    @model_serializer
    def serialize_model(self) -> dict[str, Any]:
        """Serialize message with __model__ metadata.

        Returns:
            Dictionary with serialized fields and __model__ marker.
        """
        return serialize_base_model(self)

    def init(
        self,
        sender: ActorAddress,
        team_id: uuid.UUID | None = None,
        current_message: Message | None = None,
    ) -> Message:
        """Initialize message with sender context.

        Args:
            sender: The actor sending this message.
            team_id: Optional team identifier.
            current_message: Parent message for threading.

        Returns:
            Self for method chaining.
        """
        self.parent_id = current_message.id if current_message else None
        self.team_id = uuid.UUID(str(team_id)) if isinstance(team_id, str) else team_id
        self.sender = sender
        return self


@dataclass
class StopRecursively:
    """Message to stop an actor and all its children.

    Signals that the receiving actor should stop processing and
    propagate the stop signal to all child actors.
    """

    pass


class UserMessage(Message):
    """User-generated message with human display type.

    Represents messages originating from human users in the system.

    Attributes:
        display_type: Always "human" for user messages.
        content: The message content from the user.
    """

    display_type: Literal["human"] = "human"
    content: str


class ResultMessage(Message):
    """AI-generated result message.

    Represents responses generated by AI agents in the system.

    Attributes:
        display_type: Always "ai" for AI responses.
        content: The AI-generated content.
    """

    display_type: Literal["ai"] = "ai"
    content: str
